### ISSUE TITLE
Startup lag ?  

### ISSUE THREAD

**Issue by jdeltoft** [leisim/logger_flutter#12]
I am using with the shake to view logger viewer and it works but seems to miss logs at the start.  The logs show in Android studio but a few lines are missing in the phone viewer.  Any idea how to improve?

**Comment by sanxianlee** [comment]
```
var logger = Logger(printer: PrettyPrinter(), output: ExampleLogOutput());

class ExampleLogOutput extends ConsoleOutput {
  @override
  void output(OutputEvent event) {
    super.output(event);
    LogConsole.add(event, bufferSize: 200);  // bufferSize: log display number
  }
}
```

**Comment by jdeltoft** [comment]
I've not really been using this now, so if you want to keep just reopen.  I am not sure what the comment does to help but since I'm not really using...
